title: DV Stats
name: 2021 Diversity Visa Statistics
email: dv@frankgh.com
description: >-
  We are 2021 Diversity Visa winners that are fighting for our chance to
  immigrate into the United States. This is not an official source of
  information. However, we make strides to provide accurate data extracted
  from the CEAC Official Website.
twitter_username: frankgh
github_username:  frankgh

# Build settings
theme: jekyll-theme-cayman